config/routes.rb
Rails.application.routes.draw do
  root to: "links#new"
  resources :links, only: [:new, :create]
  get ":slug/info", to: "links#info", as: "info"
  get ":slug", to: "links#show", as: "link"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/click.rb
class Click < ApplicationRecord
  belongs_to :link
end

app/models/link.rb
class Link < ApplicationRecord
  require 'mechanize'

  has_many :clicks
  before_save :generate_slug

  validates :full_url, presence: true, format: URI::regexp(%w[http https])

  def generate_slug
    self.slug = SecureRandom.alphanumeric(4)
  end

  def title
    Mechanize.new.get(full_url).title
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: %i[ show info ]

  # GET /links/1 or /links/1.json
  def show
    @link.clicks.create(ip_address: request.remote_ip)
    redirect_to @link.full_url
  end

  # GET /links/new
  def new
    @link = Link.new
  end

  # GET /links/1/info
  def info
  end

  # POST /links or /links.json
  def create
    @link = Link.new(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to info_path(@link.slug), notice: "Link was successfully created." }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { redirect_to new_link_path, alert: @link.errors.full_messages.join(", ") }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find_by(slug: params[:slug])
    end

    # Only allow a list of trusted parameters through.
    def link_params
      params.require(:link).permit(:full_url, :title, :slug)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TinyUrl</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="">
      <%flash.each do |msg_type, msg|%>
        <div class="alert alert-<%= msg_type %> alert-dismissible fade in" id="flash" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <%= msg %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/links/info.html.erb
<div class="row justify-content-md-center">
  <div class="col-md-8">
    <div class="container-fluid edit-link-container">
      <ul class="list-group details-manage">
        <li class="list-group-item">
          <span class="details"><%= @link.title %></span>
        </li>
        <li class="list-group-item">
          Shortened URL: <%= link_to "#{request.base_url}/#{@link.slug}", link_path(@link.slug), target: "_blank"%>
        </li>
        <li class="list-group-item">
          Clicks
          <ul class="list-group scrollable">
            <% @link.clicks.each do |click| %>
              <li class="list-group-item">
                <span class="details"><%= click.ip_address %></span>
                <span class="details text-right"><%= click.created_at.strftime("Clicked on %m/%d/%Y %I:%M%p") %></span>
              </li>
            <% end %>
          </ul>
        </li>
      </ul>
      <%= link_to 'New', new_link_path %>
    </div>
  </div>
</div>

app/views/links/new.html.erb
<h1 class="text-center mt-4">Shorten Link</h1>

<header class="intro">
  <div class="container">
    <div class="text-center">
      <h2 class="welcome">Shorten your links!</h2>
    </div>
    <div class="row justify-content-md-center">
      <div class="col-md-8 col-md-offset-2">
          <div class="shorten-container">
            <%= form_for :link, url: links_path, method: :post do |f| %>
              <div class="input-group mb-3">
                <%= f.text_field :full_url, class: 'panel panel-default form-control original_url',
                    required: true, placeholder: "Paste long URL to shorten" %>
                <%= f.submit "Shorten ", class: "btn btn-shorten" %>
              </div>
            <% end %>
          </div>
      </div>
    </div>
  </div>
</header>